In [35]:
import h5py
import numpy as np
import pandas as pd

In [60]:
df_jan = pd.read_csv("202001-citibike-tripdata.csv")
df_feb = pd.read_csv("202002-citibike-tripdata.csv")

df_jan.loc[:, 'starttime'] = pd.to_datetime(df_jan['starttime'])
df_feb.loc[:, 'starttime'] = pd.to_datetime(df_feb['starttime'])

df_jan.loc[:, 'stoptime'] = pd.to_datetime(df_jan['stoptime'])
df_feb.loc[:, 'stoptime'] = pd.to_datetime(df_feb['stoptime'])

In [61]:
temp_jan = df_jan[(df_jan['starttime'] >= pd.to_datetime("2020-01-13 00:00:00")) & (df_jan['stoptime'] <= pd.to_datetime("2020-01-31 23:59:59"))].reset_index()

In [62]:
temp_feb = df_feb[(df_feb['starttime'] >= pd.to_datetime("2020-02-01 00:00:00")) & (df_feb['stoptime'] <= pd.to_datetime("2020-02-09 23:59:59"))].reset_index()

In [63]:
temp_jan['starttime'] = temp_jan['starttime'].astype(str).str[:19]
temp_jan['stoptime'] = temp_jan['stoptime'].astype(str).str[:19]

temp_feb['starttime'] = temp_feb['starttime'].astype(str).str[:19]
temp_feb['stoptime'] = temp_feb['stoptime'].astype(str).str[:19]

In [64]:
temp_jan

,index,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,480044,578,2020-01-13 00:00:00,2020-01-13 00:09:39,3611,Vernon Blvd & 47 Rd,40.744907,-73.953457,3129,Queens Plaza North & Crescent St,40.751102,-73.940737,29403,Subscriber,1977,1
1,480045,238,2020-01-13 00:00:02,2020-01-13 00:04:01,3236,W 42 St & Dyer Ave,40.758985,-73.993800,477,W 41 St & 8 Ave,40.756405,-73.990026,30365,Subscriber,1981,1
2,480046,316,2020-01-13 00:00:03,2020-01-13 00:05:19,3307,West End Ave & W 94 St,40.794165,-73.974124,3320,Central Park West & W 100 St,40.794067,-73.962868,27753,Subscriber,1981,1
3,480047,365,2020-01-13 00:00:05,2020-01-13 00:06:11,471,Grand St & Havemeyer St,40.712868,-73.956981,471,Grand St & Havemeyer St,40.712868,-73.956981,38782,Subscriber,1992,2
4,480048,338,2020-01-13 00:00:22,2020-01-13 00:06:00,3812,University Pl & E 14 St,40.734814,-73.992085,280,E 10 St & 5 Ave,40.733320,-73.995101,40053,Customer,1969,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
760403,1240535,358,2020-01-31 23:53:54,2020-01-31 23:59:52,3496,1 Ave & E 110 St,40.792327,-73.938300,3374,Central Park North & Adam Clayton Powell Blvd,40.799484,-73.955613,40061,Subscriber,1983,1
760404,1240540,194,2020-01-31 23:54:41,2020-01-31 23:57:55,3414,Bergen St & Flatbush Ave,40.680945,-73.975673,3537,Carlton Ave & Dean St,40.680974,-73.971010,15079,Subscriber,1993,2
760405,1240555,149,2020-01-31 23:56:28,2020-01-31 23:58:58,3167,Amsterdam Ave & W 73 St,40.779668,-73.980930,3164,Columbus Ave & W 72 St,40.777057,-73.978985,24356,Subscriber,1966,1
760406,1240556,111,2020-01-31 23:56:35,2020-01-31 23:58:27,3306,10 St & 7 Ave,40.666208,-73.981999,3310,14 St & 7 Ave,40.663779,-73.983968,17612,Subscriber,1976,1
760407,1240569,91,2020-01-31 23:57:56,2020-01-31 23:59:27,420,Clermont Ave & Lafayette Ave,40.687645,-73.969689,397,Fulton St & Clermont Ave,40.684157,-73.969223,39809,Subscriber,1991,1

In [65]:
df = pd.concat([temp_jan, temp_feb]).reset_index()

df.loc[:, 'starttime'] = pd.to_datetime(df['starttime'])
df.loc[:, 'starttime'] = pd.to_datetime(df['starttime'])

df

,level_0,index,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,0,480044,578,2020-01-13 00:00:00,2020-01-13 00:09:39,3611,Vernon Blvd & 47 Rd,40.744907,-73.953457,3129,Queens Plaza North & Crescent St,40.751102,-73.940737,29403,Subscriber,1977,1
1,1,480045,238,2020-01-13 00:00:02,2020-01-13 00:04:01,3236,W 42 St & Dyer Ave,40.758985,-73.993800,477,W 41 St & 8 Ave,40.756405,-73.990026,30365,Subscriber,1981,1
2,2,480046,316,2020-01-13 00:00:03,2020-01-13 00:05:19,3307,West End Ave & W 94 St,40.794165,-73.974124,3320,Central Park West & W 100 St,40.794067,-73.962868,27753,Subscriber,1981,1
3,3,480047,365,2020-01-13 00:00:05,2020-01-13 00:06:11,471,Grand St & Havemeyer St,40.712868,-73.956981,471,Grand St & Havemeyer St,40.712868,-73.956981,38782,Subscriber,1992,2
4,4,480048,338,2020-01-13 00:00:22,2020-01-13 00:06:00,3812,University Pl & E 14 St,40.734814,-73.992085,280,E 10 St & 5 Ave,40.733320,-73.995101,40053,Customer,1969,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1111160,350752,350843,347,2020-02-09 23:53:43,2020-02-09 23:59:31,3744,1 Ave & E 5 St,40.725864,-73.986389,504,1 Ave & E 16 St,40.732219,-73.981656,38859,Subscriber,1963,1
1111161,350753,350845,304,2020-02-09 23:54:09,2020-02-09 23:59:14,486,Broadway & W 29 St,40.746201,-73.988557,505,6 Ave & W 33 St,40.749013,-73.988484,17287,Subscriber,1988,1
1111162,350754,350859,220,2020-02-09 23:55:08,2020-02-09 23:58:48,489,10 Ave & W 28 St,40.750664,-74.001768,212,W 16 St & The High Line,40.743349,-74.006818,39290,Subscriber,1995,1
1111163,350755,350860,218,2020-02-09 23:55:10,2020-02-09 23:58:48,489,10 Ave & W 28 St,40.750664,-74.001768,212,W 16 St & The High Line,40.743349,-74.006818,20934,Subscriber,1995,1
1111164,350756,350861,83,2020-02-09 23:55:12,2020-02-09 23:56:36,3232,Bond St & Fulton St,40.689622,-73.983043,3486,Schermerhorn St & Bond St,40.688417,-73.984517,39468,Subscriber,1963,1

In [66]:
df.to_csv("test_raw.csv")

In [67]:
manhattan_dimensions = {
    'min_latitude': 40.69331716,
    'max_latitude': 40.76915505,
    'min_longitude': -74.01713445,
    'max_longitude': -73.95381995
    }

grid_rows = 16
grid_cols = 8


class DataHandler():

    def __init__(self, datapath):
        self.df = self.load_manhattan_data(datapath)
        self.data_intervals = self.return_timestamp_intervals("2020-01-13 00:00:00", "2020-02-09 23:59:59")


    def is_in_manhattan(self, latitude, longitude):        
        return (manhattan_dimensions['min_latitude'] <= latitude <= manhattan_dimensions['max_latitude'] and
                manhattan_dimensions['min_longitude'] <= longitude <= manhattan_dimensions['max_longitude'])
    


    def load_manhattan_data(self, datapath):
        df = pd.read_csv(datapath)

        manhattan_filter = (df.apply(lambda row: self.is_in_manhattan(row['start station latitude'], row['start station longitude']) and
                                                 self.is_in_manhattan(row['end station latitude'], row['end station longitude']), axis=1))

        df = df[manhattan_filter]

        df.loc[:, 'starttime'] = pd.to_datetime(df['starttime'])
        df.loc[:, 'stoptime'] = pd.to_datetime(df['stoptime'])

        return df
    


    def return_timestamp_intervals(self, start_time, end_time):
        dates = []

        for start_date in pd.date_range(start=start_time, end=end_time, freq='30T'):
            end_date = start_date + pd.Timedelta(minutes=30)
            
            dates.append([start_date, end_date])

        return dates
    

    
    def create_matrix(self, station_counts):
        # Calculate step sizes for latitude and longitude
        lat_step = (manhattan_dimensions['max_latitude'] - manhattan_dimensions['min_latitude']) / grid_rows #roughly 0.01108 degrees
        lon_step = (manhattan_dimensions['max_longitude'] - manhattan_dimensions['min_longitude']) / grid_cols #roughly 0.0136125 degrees

        grid = np.zeros((grid_rows, grid_cols))

        for index, row in station_counts.iterrows():
            station_lat = row['station latitude']
            station_lon = row['station longitude']
            station_traffic = row["count"]
            
            # Check if the current cell contains the bike station
            for i in range(grid_rows):

                for j in range(grid_cols):

                    lat_min = manhattan_dimensions['min_latitude'] + i * lat_step
                    lat_max = lat_min + lat_step

                    lon_min = manhattan_dimensions['min_longitude'] + j * lon_step
                    lon_max = lon_min + lon_step
                    
                    if lat_min <= station_lat < lat_max and lon_min <= station_lon < lon_max:
                        grid[i][j] += station_traffic

        # Reverse grid so that bottom of the grid now represents bottom of Manhattan
        return grid[::-1]



    def generate_inflow_matrix(self, start_interval, stop_interval):
        # Filter rows for a specific date, e.g., '2014-01-01'
        temp_df = self.df[(self.df['stoptime'] >= pd.to_datetime(start_interval)) & (self.df['stoptime'] <= pd.to_datetime(stop_interval))]

        # Print the filtered DataFrame
        stop_df = temp_df.drop(columns=[
                    "tripduration",
                    "starttime",
                    "start station id", 
                    "start station name", 
                    "start station latitude", 
                    "start station longitude", 
                    "bikeid", 
                    "usertype", 
                    "birth year", 
                    "gender"
                    ])

        stop_df.rename(columns = {
                                "end station id": "station id",
                                "end station name": "station name",
                                "end station latitude": "station latitude", 
                                "end station longitude": "station longitude"
                                }, inplace = True)

        station_counts = stop_df.groupby(['station id', 'station name', 'station latitude', 'station longitude']).size().reset_index(name='count')
        inflow_matrix = self.create_matrix(station_counts)

        return inflow_matrix   



    def generate_outflow_matrix(self, start_interval, stop_interval):
        # Filter rows for a specific date, e.g., '2014-01-01'
        temp_df = self.df[(self.df['starttime'] >= pd.to_datetime(start_interval)) & (self.df['starttime'] <= pd.to_datetime(stop_interval))]

        # Print the filtered DataFrame
        start_df = temp_df.drop(columns=[
                    "tripduration",
                    "stoptime",
                    "end station id", 
                    "end station name", 
                    "end station latitude", 
                    "end station longitude", 
                    "bikeid", 
                    "usertype", 
                    "birth year", 
                    "gender"
                    ])
        
        start_df.rename(columns = {
                          "start station id": "station id",
                          "start station name": "station name",
                          "start station latitude": "station latitude", 
                          "start station longitude": "station longitude"
                          }, inplace = True)
        
        station_counts = start_df.groupby(['station id', 'station name', 'station latitude', 'station longitude']).size().reset_index(name='count')
        
        outflow_matrix = self.create_matrix(station_counts)

        return outflow_matrix
    
        

    def generate_dataset(self):
        traffic_data = []
        dates = []

        for entry in range(len(self.data_intervals)):
            start_interval, stop_interval = self.data_intervals[entry]

            inflow_matrix = self.generate_inflow_matrix(start_interval, stop_interval)
            outflow_matrix = self.generate_outflow_matrix(start_interval, stop_interval)

            matrices = (outflow_matrix, inflow_matrix)

            traffic_data.append(matrices)
            dates.append(stop_interval.strftime('%Y%m%d%H%M'))

    
        with h5py.File('test_dataset.h5', 'w') as hf:
            # Store dates as strings
            hf.create_dataset('timeslot', data=dates)
            hf.create_dataset('trip', data=traffic_data)

In [68]:
a = DataHandler('test_raw.csv')
a.generate_dataset()

In [73]:
# Specify the path to your HDF5 file
file_path = 'test_dataset.h5'

# Open the HDF5 file in read mode
with h5py.File(file_path, 'r') as f:
    # Access the trip dataset and their corresponding timestamps
    traffic_data = f['trip'][()]
    dates = f['timeslot'][()]

traffic_data[0]

array([[[0., 0., 0., 0., 1., 2., 1., 0.],
        [0., 0., 1., 2., 1., 1., 0., 0.],
        [0., 1., 1., 3., 1., 0., 0., 0.],
        [0., 0., 2., 2., 1., 0., 3., 0.],
        [0., 3., 0., 1., 1., 0., 0., 0.],
        [0., 2., 4., 2., 1., 7., 0., 0.],
        [0., 0., 1., 1., 0., 0., 0., 0.],
        [0., 3., 1., 4., 1., 0., 0., 0.],
        [0., 2., 5., 6., 3., 0., 0., 0.],
        [0., 2., 0., 3., 2., 0., 0., 0.],
        [0., 1., 0., 4., 1., 0., 0., 0.],
        [1., 1., 0., 2., 1., 0., 0., 1.],
        [1., 2., 0., 0., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 1., 0.]],

       [[0., 0., 0., 1., 1., 0., 0., 0.],
        [0., 0., 0., 1., 1., 0., 0., 2.],
        [0., 0., 0., 4., 0., 1., 0., 0.],
        [0., 1., 0., 3., 1., 1., 0., 0.],
        [0., 2., 0., 0., 1., 3., 0., 0.],
        [0., 0., 0., 1., 1., 2., 0., 0.],
        [0., 1., 2., 0., 0., 0., 0., 0.],
        [0., 1., 1., 2., 1., 0., 0., 0.],
        [0., 3., 1., 5., 2., 0., 0., 0.],
        [1., 0., 1., 2., 1., 1., 0., 0.],
        [1., 1., 0., 0., 2., 0., 0., 0.],
        [0., 0., 2., 1., 0., 0., 0., 1.],
        [0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]]])